### ISSUE TITLE
Semantic UI: semantic.min.css not properly built

### ISSUE THREAD

**Issue by codydh** [YABhq/Laracogs#62]
I'm following the steps for beginning with Laracogs, I successfully add the starter kit, and then move to add Semantic UI.

I run `php artisan laracogs:semantic` and am presented with these instructions:

```
You will need to install semantic-ui:
npm install semantic-ui

When prompted set the directory to:
semantic

Then run:
cd semantic && gulp build

Then run:
cd ../ && gulp

Make sure you set the PagesController@dashboard to use the following view:
'dashboard.main'

Finished setting up semantic-ui in your app
```

I successfully run `npm install semantic-ui`.

When running `cd semantic && gulp build`, I get the following error:

```
Potentially unhandled rejection [2] TypeError: Cannot call method 'match' of undefined
    at DestroyableTransform.module.exports.settings.plumber.less.errorHandler (/home/cdehaan/prism-laracogs/semantic/tasks/config/tasks.js:96:29)
    at DestroyableTransform.emit (events.js:117:20)
    at afterTransform (/home/cdehaan/prism-laracogs/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:74:26)
    at TransformState.afterTransform (/home/cdehaan/prism-laracogs/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at /home/cdehaan/prism-laracogs/node_modules/gulp-less/index.js:58:14
    at tryCatchReject (/home/cdehaan/prism-laracogs/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/home/cdehaan/prism-laracogs/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/home/cdehaan/prism-laracogs/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/home/cdehaan/prism-laracogs/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/home/cdehaan/prism-laracogs/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/Scheduler.js:62:19)
```

And then when I get to the `cd ../ && gulp` step, I get the following output:

```
[cdehaan@localhost prism-laracogs]$ gulp
[12:00:23] Using gulpfile ~/prism-laracogs/gulpfile.js
[12:00:23] Starting 'default'...
[12:00:23] Starting 'copy'...

Fetching Copy Source Files...
   - semantic/dist/semantic.min.css <-- Not Found


Saving To...
   - public/css/semantic.min.css

[12:00:23] Finished 'default' after 41 ms
[12:00:23] Finished 'copy' after 44 ms
[12:00:23] Starting 'sass'...

Fetching Sass Source Files...
   - resources/assets/sass/app.scss


Saving To...
   - public/css/app.css

[12:00:23] gulp-notify: [Laravel Elixir] Sass Compiled!
[12:00:23] Finished 'sass' after 857 ms
[12:00:23] Starting 'copy'...

Fetching Copy Source Files...
   - semantic/dist/semantic.min.js


Saving To...
   - public/js/semantic.min.js

[12:00:23] Finished 'copy' after 15 ms
[12:00:23] Starting 'scripts'...

Fetching Scripts Source Files...
   - resources/assets/js/app.js


Saving To...
   - public/js/all.js

[12:00:24] gulp-notify: [Laravel Elixir] Scripts Merged!
[12:00:24] Finished 'scripts' after 635 ms
```

So semantic.min.css is not properly built.

**Comment by mlantz** [comment]
Everything works fine for me in a fresh install of Laravel with Laracogs. If you have previously attempted to build semantic and have issues, the best thing to do is delete the semantic directory and semantic.json and then try again.
