### ISSUE TITLE
CRUD builder error with example data (or custom data)

### ISSUE THREAD

**Issue by studiovlijmscherp** [YABhq/Laracogs#92]
**Tried to run:**
php artisan crudmaker:new Bike --migration --schema="id:increments,title:string,author:string"

**console returns error:**
  6/7 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░]  85%
  [Exception]
  Unable to generate your CRUD: Undefined offset: 2

**Sysinfo:**
Laravel Framework version 5.3.18
laracogs version 2.1
PHP 5.6

**Laravel log displays:**

```
[2016-10-14 14:46:29] local.ERROR: exception 'Exception' with message 'Unable to generate your CRUD: Undefined offset: 2' in /Users/michielzoer/Projecten/GIT/moodstudios-app/project/vendor/yab/crudmaker/src/Console/CrudMaker.php:241
Stack trace:
#0 /Users/michielzoer/Projecten/GIT/moodstudios-app/project/vendor/yab/crudmaker/src/Console/CrudMaker.php(197): Yab\CrudMaker\Console\CrudMaker->createCRUD(Array, '', 'Bike', Array)
#1 [internal function]: Yab\CrudMaker\Console\CrudMaker->handle()
#2 /Users/michielzoer/Projecten/GIT/moodstudios-app/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#3 /Users/michielzoer/Projecten/GIT/moodstudios-app/project/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#4 /Users/michielzoer/Projecten/GIT/moodstudios-app/project/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /Users/michielzoer/Projecten/GIT/moodstudios-app/project/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Users/michielzoer/Projecten/GIT/moodstudios-app/project/vendor/symfony/console/Application.php(820): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/michielzoer/Projecten/GIT/moodstudios-app/project/vendor/symfony/console/Application.php(187): Symfony\Component\Console\Application->doRunCommand(Object(Yab\CrudMaker\Console\CrudMaker), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/michielzoer/Projecten/GIT/moodstudios-app/project/vendor/symfony/console/Application.php(118): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Users/michielzoer/Projecten/GIT/moodstudios-app/project/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /Users/michielzoer/Projecten/GIT/moodstudios-app/project/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 {main}  
```

**Comment by mlantz** [comment]
Found the issue and pushed a new release of CrudMaker with the fix. Run composer update and try again, the problem should be solved.
